server:
  port: 8082
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DB_URL:jdbc:postgresql://localhost:5432/ecommerce_catalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:you123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        connection:
          provider_disables_autocommit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 30MB

file:
  upload-dir: uploads/products

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
